/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignmentjava;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Homepage extends javax.swing.JFrame {
        
    public static String user;
    /**
     * Creates new form Homepage
     */
    public Homepage(String userName) {
        initComponents();
        user = userName;
        welcome(user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnViewBook = new javax.swing.JButton();
        btnBookManagement = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnFB = new javax.swing.JButton();
        btnGmail = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnGGclass = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        btnViewBook.setBackground(new java.awt.Color(0, 153, 255));
        btnViewBook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnViewBook.setForeground(new java.awt.Color(255, 255, 255));
        btnViewBook.setText("View Book informations");
        btnViewBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBookActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 50));

        btnBookManagement.setBackground(new java.awt.Color(0, 153, 255));
        btnBookManagement.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBookManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnBookManagement.setText("Book management");
        btnBookManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookManagementActionPerformed(evt);
            }
        });
        getContentPane().add(btnBookManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 190, 50));

        btnExit.setBackground(new java.awt.Color(153, 0, 0));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit program");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 120, 50));

        btnFB.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive\\Documents\\NetBeansProjects\\AssignmentJava\\src\\fb1.jpg")); // NOI18N
        btnFB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFBActionPerformed(evt);
            }
        });
        getContentPane().add(btnFB, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 60, 60));

        btnGmail.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive\\Documents\\NetBeansProjects\\AssignmentJava\\src\\gmail..1.jpg")); // NOI18N
        btnGmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGmailActionPerformed(evt);
            }
        });
        getContentPane().add(btnGmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 60, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("Our sites: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 70, -1));

        btnGGclass.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive\\Documents\\NetBeansProjects\\AssignmentJava\\src\\1ggclassroom.jpg")); // NOI18N
        btnGGclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGGclassActionPerformed(evt);
            }
        });
        getContentPane().add(btnGGclass, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 60, -1));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFBActionPerformed
        // TODO add your handling code here:
        Desktop browser = Desktop.getDesktop();
        try {
            browser.browse(new URI("https://www.facebook.com/AnhTungmang/"));
        } catch (URISyntaxException ex) {

        } catch (IOException ex) {

        }
    }//GEN-LAST:event_btnFBActionPerformed

    private void btnViewBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBookActionPerformed

        ViewBook bookList = new ViewBook(user);
        bookList.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnViewBookActionPerformed

    private void btnBookManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookManagementActionPerformed
        // TODO add your handling code here:
        BookManagement bm = new BookManagement(user);
        bm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBookManagementActionPerformed

    private void btnGmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGmailActionPerformed
        // TODO add your handling code here:
        Desktop browser = Desktop.getDesktop();
        try {
            browser.browse(new URI("https://mail.google.com/"));
        } catch (URISyntaxException ex) {

        } catch (IOException ex) {

        }
    }//GEN-LAST:event_btnGmailActionPerformed

    private void btnGGclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGGclassActionPerformed
        // TODO add your handling code here:
        Desktop browser = Desktop.getDesktop();
        try {
            browser.browse(new URI("https://classroom.google.com/u/1/c/NDk4Nzg0NzA1Mzgw"));
        } catch (URISyntaxException ex) {

        } catch (IOException ex) {

        }
    }//GEN-LAST:event_btnGGclassActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookManagement;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFB;
    private javax.swing.JButton btnGGclass;
    private javax.swing.JButton btnGmail;
    private javax.swing.JButton btnViewBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    void welcome(String user){
        jLabel1.setText("Welcome, " + user);
        if(user.equalsIgnoreCase("admin")){
            btnViewBook.setVisible(false);
            btnBookManagement.setVisible(true);
        }
        else{
            btnViewBook.setVisible(true);
            btnBookManagement.setVisible(false);
        }
    }

}
